gen-client:
    openapi-generator-cli generate -i ../openapi.yaml -g dart -o ./gen_api

gen-icons:
    flutter pub get
    dart run flutter_launcher_icons

dev: gen-client gen-icons
    flutter run
    
