name: Yausma
description: Yet Another Useless Stock Market App.
publish_to: none
version: 1.7.0+24
environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  openapi:
    path: ./gen_api
  flutter:
    sdk: flutter
  provider: ^6.1.1
  fluttertoast: ^8.0.9
  flutter_svg: <2.1.0
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.2
  fl_chart: ^0.55.2
dev_dependencies:
  flutter_launcher_icons: ^0.13.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: launcher_icon
  ios: false
  image_path: ../assets/icon.png
  min_sdk_android: 21
flutter:
  uses-material-design: true
