/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NewsItem from './NewsItem';

/**
 * The MarketOverviewItem model module.
 * @module model/MarketOverviewItem
 * @version 0.1.0
 */
class MarketOverviewItem {
    /**
     * Constructs a new <code>MarketOverviewItem</code>.
     * @alias module:model/MarketOverviewItem
     * @param name {String} 
     * @param _short {String} 
     * @param sector {String} 
     * @param currentPrice {String} 
     * @param change {Number} 
     * @param high {Number} 
     * @param low {Number} 
     * @param symbol {String} 
     * @param volume {Number} 
     */
    constructor(name, _short, sector, currentPrice, change, high, low, symbol, volume) { 
        
        MarketOverviewItem.initialize(this, name, _short, sector, currentPrice, change, high, low, symbol, volume);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, _short, sector, currentPrice, change, high, low, symbol, volume) { 
        obj['name'] = name;
        obj['short'] = _short;
        obj['sector'] = sector;
        obj['current_price'] = currentPrice;
        obj['change'] = change;
        obj['high'] = high;
        obj['low'] = low;
        obj['symbol'] = symbol;
        obj['volume'] = volume;
    }

    /**
     * Constructs a <code>MarketOverviewItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MarketOverviewItem} obj Optional instance to populate.
     * @return {module:model/MarketOverviewItem} The populated <code>MarketOverviewItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MarketOverviewItem();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('short')) {
                obj['short'] = ApiClient.convertToType(data['short'], 'String');
            }
            if (data.hasOwnProperty('sector')) {
                obj['sector'] = ApiClient.convertToType(data['sector'], 'String');
            }
            if (data.hasOwnProperty('current_price')) {
                obj['current_price'] = ApiClient.convertToType(data['current_price'], 'String');
            }
            if (data.hasOwnProperty('change')) {
                obj['change'] = ApiClient.convertToType(data['change'], 'Number');
            }
            if (data.hasOwnProperty('high')) {
                obj['high'] = ApiClient.convertToType(data['high'], 'Number');
            }
            if (data.hasOwnProperty('low')) {
                obj['low'] = ApiClient.convertToType(data['low'], 'Number');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('volume')) {
                obj['volume'] = ApiClient.convertToType(data['volume'], 'Number');
            }
            if (data.hasOwnProperty('news_article')) {
                obj['news_article'] = ApiClient.convertToType(data['news_article'], NewsItem);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MarketOverviewItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MarketOverviewItem</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MarketOverviewItem.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['short'] && !(typeof data['short'] === 'string' || data['short'] instanceof String)) {
            throw new Error("Expected the field `short` to be a primitive type in the JSON string but got " + data['short']);
        }
        // ensure the json data is a string
        if (data['sector'] && !(typeof data['sector'] === 'string' || data['sector'] instanceof String)) {
            throw new Error("Expected the field `sector` to be a primitive type in the JSON string but got " + data['sector']);
        }
        // ensure the json data is a string
        if (data['current_price'] && !(typeof data['current_price'] === 'string' || data['current_price'] instanceof String)) {
            throw new Error("Expected the field `current_price` to be a primitive type in the JSON string but got " + data['current_price']);
        }
        // ensure the json data is a string
        if (data['symbol'] && !(typeof data['symbol'] === 'string' || data['symbol'] instanceof String)) {
            throw new Error("Expected the field `symbol` to be a primitive type in the JSON string but got " + data['symbol']);
        }
        // validate the optional field `news_article`
        if (data['news_article']) { // data not null
          NewsItem.validateJSON(data['news_article']);
        }

        return true;
    }


}

MarketOverviewItem.RequiredProperties = ["name", "short", "sector", "current_price", "change", "high", "low", "symbol", "volume"];

/**
 * @member {String} name
 */
MarketOverviewItem.prototype['name'] = undefined;

/**
 * @member {String} short
 */
MarketOverviewItem.prototype['short'] = undefined;

/**
 * @member {String} sector
 */
MarketOverviewItem.prototype['sector'] = undefined;

/**
 * @member {String} current_price
 */
MarketOverviewItem.prototype['current_price'] = undefined;

/**
 * @member {Number} change
 */
MarketOverviewItem.prototype['change'] = undefined;

/**
 * @member {Number} high
 */
MarketOverviewItem.prototype['high'] = undefined;

/**
 * @member {Number} low
 */
MarketOverviewItem.prototype['low'] = undefined;

/**
 * @member {String} symbol
 */
MarketOverviewItem.prototype['symbol'] = undefined;

/**
 * @member {Number} volume
 */
MarketOverviewItem.prototype['volume'] = undefined;

/**
 * @member {module:model/NewsItem} news_article
 */
MarketOverviewItem.prototype['news_article'] = undefined;






export default MarketOverviewItem;

