/**
 * YAUSMA NewsItem Model - Browser Compatible
 * Converted from ES6 class to browser-compatible JavaScript
 * 
 * The version of the OpenAPI document: 0.1.0
 * 
 * NOTE: This was auto generated by OpenAPI Generator and converted for browser compatibility.
 * https://openapi-generator.tech
 */

/**
 * Constructs a new NewsItem.
 * @param {String} id News item ID
 * @param {String} title News title
 * @param {String} publisher News publisher
 * @param {String} source News source
 * @param {String} date Publication date
 */
function NewsItem(id, title, publisher, source, date) {
    NewsItem.initialize(this, id, title, publisher, source, date);
}

/**
 * Initializes the fields of this object.
 * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
 * Only for internal use.
 */
NewsItem.initialize = function(obj, id, title, publisher, source, date) {
    obj['id'] = id;
    obj['title'] = title;
    obj['publisher'] = publisher;
    obj['source'] = source;
    obj['date'] = date;
};

/**
 * Constructs a NewsItem from a plain JavaScript object, optionally creating a new instance.
 * Copies all relevant properties from data to obj if supplied or a new instance if not.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @param {NewsItem} obj Optional instance to populate.
 * @return {NewsItem} The populated NewsItem instance.
 */
NewsItem.constructFromObject = function(data, obj) {
    if (data) {
        obj = obj || new NewsItem();

        if (data.hasOwnProperty('id')) {
            obj['id'] = (typeof ApiClient !== 'undefined') ? ApiClient.convertToType(data['id'], 'String') : data['id'];
        }
        if (data.hasOwnProperty('title')) {
            obj['title'] = (typeof ApiClient !== 'undefined') ? ApiClient.convertToType(data['title'], 'String') : data['title'];
        }
        if (data.hasOwnProperty('publisher')) {
            obj['publisher'] = (typeof ApiClient !== 'undefined') ? ApiClient.convertToType(data['publisher'], 'String') : data['publisher'];
        }
        if (data.hasOwnProperty('source')) {
            obj['source'] = (typeof ApiClient !== 'undefined') ? ApiClient.convertToType(data['source'], 'String') : data['source'];
        }
        if (data.hasOwnProperty('date')) {
            obj['date'] = (typeof ApiClient !== 'undefined') ? ApiClient.convertToType(data['date'], 'String') : data['date'];
        }
    }
    return obj;
};

/**
 * Validates the JSON data with respect to NewsItem.
 * @param {Object} data The plain JavaScript object bearing properties of interest.
 * @return {boolean} to indicate whether the JSON data is valid with respect to NewsItem.
 */
NewsItem.validateJSON = function(data) {
    // check to make sure all required properties are present in the JSON string
    for (var i = 0; i < NewsItem.RequiredProperties.length; i++) {
        var property = NewsItem.RequiredProperties[i];
        if (!data.hasOwnProperty(property)) {
            throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
        }
    }
    
    // ensure the json data is a string
    if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
        throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
    }
    // ensure the json data is a string
    if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
        throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
    }
    // ensure the json data is a string
    if (data['publisher'] && !(typeof data['publisher'] === 'string' || data['publisher'] instanceof String)) {
        throw new Error("Expected the field `publisher` to be a primitive type in the JSON string but got " + data['publisher']);
    }
    // ensure the json data is a string
    if (data['source'] && !(typeof data['source'] === 'string' || data['source'] instanceof String)) {
        throw new Error("Expected the field `source` to be a primitive type in the JSON string but got " + data['source']);
    }
    // ensure the json data is a string
    if (data['date'] && !(typeof data['date'] === 'string' || data['date'] instanceof String)) {
        throw new Error("Expected the field `date` to be a primitive type in the JSON string but got " + data['date']);
    }

    return true;
};

// Define required properties
NewsItem.RequiredProperties = ["id", "title", "publisher", "source", "date"];

/**
 * @member {String} id
 */
NewsItem.prototype['id'] = undefined;

/**
 * @member {String} title
 */
NewsItem.prototype['title'] = undefined;

/**
 * @member {String} publisher
 */
NewsItem.prototype['publisher'] = undefined;

/**
 * @member {String} source
 */
NewsItem.prototype['source'] = undefined;

/**
 * @member {String} date
 */
NewsItem.prototype['date'] = undefined;

// Make available globally
if (typeof window !== 'undefined') {
    window.NewsItem = NewsItem;
}

