/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserCredentials model module.
 * @module model/UserCredentials
 * @version 0.1.0
 */
class UserCredentials {
    /**
     * Constructs a new <code>UserCredentials</code>.
     * @alias module:model/UserCredentials
     * @param email {String} 
     * @param passwordHash {String} 
     */
    constructor(email, passwordHash) { 
        
        UserCredentials.initialize(this, email, passwordHash);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, passwordHash) { 
        obj['email'] = email;
        obj['password_hash'] = passwordHash;
    }

    /**
     * Constructs a <code>UserCredentials</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserCredentials} obj Optional instance to populate.
     * @return {module:model/UserCredentials} The populated <code>UserCredentials</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserCredentials();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password_hash')) {
                obj['password_hash'] = ApiClient.convertToType(data['password_hash'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserCredentials</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserCredentials</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserCredentials.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['password_hash'] && !(typeof data['password_hash'] === 'string' || data['password_hash'] instanceof String)) {
            throw new Error("Expected the field `password_hash` to be a primitive type in the JSON string but got " + data['password_hash']);
        }

        return true;
    }


}

UserCredentials.RequiredProperties = ["email", "password_hash"];

/**
 * @member {String} email
 */
UserCredentials.prototype['email'] = undefined;

/**
 * @member {String} password_hash
 */
UserCredentials.prototype['password_hash'] = undefined;






export default UserCredentials;

